### ISSUE TITLE
We're waiting.

### ISSUE THREAD

**Issue by defied** [tylercrumpton/robotframework-scplibrary#1]
0]

Could definitely use this. SSHLibrary uses sftp.

**Comment by tylercrumpton** [comment]
Hi there!

I started this a while back to track a Library I had created at work, but I was not very experienced in git or Python at the time, so it never got committed or pushed.

However, things have changed, so if you need it, I will build it! I've already started putting it back together with a few keywords: 'Open Connection', 'Get File', and 'Put File'.

I'll close out this ticket once I have a v1 library ready to go. It will be available on PyPi so you can pip install it, and I'm very willing to make any improvements and changes that will help you in your testing.

Thanks!

**Comment by tylercrumpton** [comment]
Version v1.0.0 is out! Let me know if you run into any problems!

**Comment by defied** [comment]
Will do! Thanks!
