### ISSUE TITLE
Importing test library 'SCPLibrary' failed

### ISSUE THREAD

**Issue by raygomez** [tylercrumpton/robotframework-scplibrary#4]
I tried using the module but I'm encountering this error.

**\* Test Cases *** 
Test With Settings
     Open Connection     ${HOST} 
    Close Connection

[ ERROR ] Error in file '/Users/user/IdeaProjects/test-framework/Rollover/Rollover Wild.robot': Importing test library 'SCPLibrary' failed: ImportError: No module named 'errors'
Traceback (most recent call last):
  File "/Users/user/robot-py/lib/python3.4/site-packages/SCPLibrary/**init**.py", line 1, in <module>
    from .library import SCPLibrary
  File "/Users/user/robot-py/lib/python3.4/site-packages/SCPLibrary/library.py", line 4, in <module>
    from errors import SCPNotConnectedError
PYTHONPATH:
  /Users/user/robot-py/bin
  /Users/user/robot-py/lib/python34.zip
  /Users/user/robot-py/lib/python3.4
  /Users/user/robot-py/lib/python3.4/plat-darwin
  /Users/user/robot-py/lib/python3.4/lib-dynload
  /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4
  /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin
  /Users/user/robot-py/lib/python3.4/site-packages

**Comment by raygomez** [comment]
I was able to fix by update library.py

+from .errors import SCPNotConnectedError
-from errors import SCPNotConnectedError

**Comment by gkeishin** [comment]
If we can get this fix for python3.x it would be really cool. Thanks, @raygomez for opening this one up. I was looking for the fix for it.

**Comment by tylercrumpton** [comment]
Just released version v1.2.0 that should fix this. Thanks for the ping!

**Comment by gkeishin** [comment]
Thanks @tylercrumpton
